### ISSUE TITLE
Error: Non-file stream objects are not supported with SigV4 in AWS.S3

### ISSUE THREAD

**Issue by pascalbayer** [matrus2/webpack-s3-uploader#2]
Webpack-s3-uploader throws the following exception `Error: Non-file stream objects are not supported with SigV4 in AWS.S3` when using S3 locations that require SigV4 e.g. "eu-central-1"

This issue seems to be related to the `node-s3-client` dependency, see: https://github.com/andrewrk/node-s3-client/issues/69.
Maybe consider switching to a different dependency like https://github.com/shreyawhiz/node-s3-client to solve the issue.

**Comment by pascalbayer** [comment]
PR #3 fixes the described issue.

**Comment by matrus2** [comment]
Fixed with commit 52f08d17c9a93845d9a63232c2906290d9b123fa
