### ISSUE TITLE
Add optional url for s3

### ISSUE THREAD

**Issue by OmgImAlexis** [matrus2/webpack-s3-uploader#4]
To be able to use [minio](https://github.com/minio/minio) with this I need to be able to set the url for "s3".

**Comment by matrus2** [comment]
Hey,
Based on this document:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

All you need to do is to have the bucket name and aws region (all aws s3 urls are constructed based on these two). If you want to upload assets to specific directory use `basePath` parameter. 

If you have further problems/questions please provide more description or minimal example showing your problem. Thx

**Comment by OmgImAlexis** [comment]
So something like this should work? `static.twistly.xyz` is my minio server. minio expects `us-east-1` for it's region. The bucket I have setup is `twistly`.

```
new S3Uploader({
    s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: 'us-east-1',
        endpoint: 'static.twistly.xyz'
    },
    s3UploadOptions: {
        Bucket: 'twistly'
    }
})
```

When using this I get an error.

```
Uploading [      ----------------------------------------------------------------------------------------------] 6% 71.4sError: UnknownEndpoint: Inaccessible host: `twistly.static.twistly.xyz'. This service may not be available in the `us-east-1' region.
    at handleErrors (/Users/xo/code/twistly-frontend/node_modules/webpack-s3-uploader/s3_uploader.js:33:6)
    at getAssetFiles.then.then.then.then.catch.e (/Users/xo/code/twistly-frontend/node_modules/webpack-s3-uploader/s3_uploader.js:92:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by matrus2** [comment]
I assume you have a s3 bucket `twistly` in `us-east-1` region and minio server is pointing to this bucket, correct? 

EDIT: Based on docs [s3Options](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property) there is no such param as `endpoint`.

**Comment by OmgImAlexis** [comment]
Minio is an object storage server compatible with Amazon S3 APIs so I'm not actually using s3 itself.

I think this is the reason it's not working. The underlying library is creating the url incorrectly for minio. The bucket url should be `http://static.twistly.xyz`. The bucket's name is twistly. Minio's region is set to accept `us-east-1`.

https://github.com/shreyawhiz/node-s3-client/blob/a06ab02fa9e7cc92b6f762ef0200423184ff12c1/lib/index.js#L1435-L1453

**Comment by matrus2** [comment]
Closing as this plugin is supposed to work directly with s3.
